name: ecom
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_storage: ^11.6.8
  cloud_firestore: ^4.15.6
  get_storage: ^2.1.1
  carousel_slider: ^4.2.1
  stylish_bottom_bar: ^1.0.3
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
