// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAorfP-fA3dYadrJOWt5jhSrDc-WWp8krU',
    appId: '1:892682749726:web:29cfe64cf52831df57eb0f',
    messagingSenderId: '892682749726',
    projectId: 'ecom-85c28',
    authDomain: 'ecom-85c28.firebaseapp.com',
    storageBucket: 'ecom-85c28.appspot.com',
    measurementId: 'G-LY0MJNME8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAimmI0xV9LIPwe9A1yB4v5EfcTBFwuRSo',
    appId: '1:892682749726:android:669d35eea2ffe99057eb0f',
    messagingSenderId: '892682749726',
    projectId: 'ecom-85c28',
    storageBucket: 'ecom-85c28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtnYJKesj6nxAbbpsCKdQ45sTIsxdBNgE',
    appId: '1:892682749726:ios:b3708301e28f60f757eb0f',
    messagingSenderId: '892682749726',
    projectId: 'ecom-85c28',
    storageBucket: 'ecom-85c28.appspot.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtnYJKesj6nxAbbpsCKdQ45sTIsxdBNgE',
    appId: '1:892682749726:ios:6aaad5ff0bf938a857eb0f',
    messagingSenderId: '892682749726',
    projectId: 'ecom-85c28',
    storageBucket: 'ecom-85c28.appspot.com',
    iosBundleId: 'com.example.ecom.RunnerTests',
  );
}
